version: '3.7'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    env_file:
      - ./.envs/.local/.openldap
    networks:
      - organization

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    env_file:
      - ./.envs/.local/.phpldapadmin
    depends_on:
      - openldap
    networks:
      - organization

networks:
  organization:
    driver: bridge
